import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from 'next/image';
import deved from "../public/homepage.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Fabbiha's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-khaki px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>lorem ipsum</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-stone-500 text-white px-4 py-2 rounded-md ml-8' href='#'>LinkedIn</a></li>
            </ul>
          </nav>
          <div className='text-left p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Fabbiha Sultana</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Junior Software Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl'>Graduated from a 16 week intensive bootcamp read to apply my newly learnt skills to real world problems.</p>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover'/>
          </div>
        </section>
        {/* second page */}
        <section>
          <div>
            <h3 className='text-3x py-1'>Project's I've worked on</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Since the start of the bootcamp in <span className='text-teal-500'>September</span>, I've worked on a wide range of projects. Lorem ipsum is dummy text used in the typing and printing industry.</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Vivamus sed rutrum ipsum. Donec rutrum tellus imperdiet rhoncus elementum. Proin nec justo et metus maximus dictum sit amet sit amet turpis. Etiam consectetur diam vitae odio sollicitudin tincidunt. Vivamus nibh orci, mollis ultrices lobortis venenatis, vulputate sit amet mauris</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Vulputate sit amet mauris</h3>
              <p className='py-2'>Vivamus vel lacus et libero mollis suscipit. Etiam justo arcu, congue vitae nibh at, ultrices facilisis lorem. Nam nec mi turpis. Donec sagittis sapien eget commodo tincidunt. </p>
              <h4 className='py-4 text-teal-600'>Tech stack</h4>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>React.js</p>
              <p className='text-gray-800 py-1'>PostgreSQL</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Vulputate sit amet mauris</h3>
              <p className='py-2'>Vivamus vel lacus et libero mollis suscipit. Etiam justo arcu, congue vitae nibh at, ultrices facilisis lorem. Nam nec mi turpis. Donec sagittis sapien eget commodo tincidunt. </p>
              <h4 className='py-4 text-teal-600'>Tech stack</h4>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>React.js</p>
              <p className='text-gray-800 py-1'>PostgreSQL</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Vulputate sit amet mauris</h3>
              <p className='py-2'>Vivamus vel lacus et libero mollis suscipit. Etiam justo arcu, congue vitae nibh at, ultrices facilisis lorem. Nam nec mi turpis. Donec sagittis sapien eget commodo tincidunt. </p>
              <h4 className='py-4 text-teal-600'>Tech stack</h4>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>React.js</p>
              <p className='text-gray-800 py-1'>PostgreSQL</p>
            </div>
          </div>
        </section>
        <section>
        </section>
      </main>
    </div>
  );
}
